//
//  LocationMasterList.swift
//  YardRemote Dev
//
//  Created by Felipe Galindo on 1/2/21.
//

import Foundation
//
var LocationMasterListJSON = """
[
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "",
    "address": "4714 Otsego St.",
    "propertyManagerName": "-",
    "lg": true,
    "isActive": true,
    "snowRemoval": true,
    "lawnCare": true,
    "scheduleLawnCare": "Biweekly-Mon",
    "priceLawnCareVisit": "$30",
    "email": "djohnso3@d.umn.edu",
    "phone": "",
    "notesLawnCare": "",
    "salt": "Yes/Maybe",
    "triggerSnowRemoval": "1 inch",
    "billingStructureSnowRemoval": "Per Push",
    "snowRemovalZeroToFive": "25",
    "snowRemovalFiveToTen": "$40",
    "snowRemovalTenToFifthteen": "$55",
    "snowRemovalFifthteenToTwenty": "$75",
    "hourlyRateSnowRemoval": "$35/hour",
    "billingScheduleSnowRemoval": "",
    "notesSnowRemoval": "",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  },
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "Residential Clients",
    "address": "3423 Woodland Ave",
    "propertyManagerName": "Alice",
    "lg": true,
    "isActive": true,
    "snowRemoval": true,
    "lawnCare": true,
    "scheduleLawnCare": "Weekly",
    "priceLawnCareVisit": "$45",
    "email": "",
    "phone": "218-591-7972",
    "notesLawnCare": "",
    "salt": "Yes/Maybe",
    "triggerSnowRemoval": "1 inches",
    "billingStructureSnowRemoval": "Per Push",
    "snowRemovalZeroToFive": "$45",
    "snowRemovalFiveToTen": "$65",
    "snowRemovalTenToFifthteen": "$85",
    "snowRemovalFifthteenToTwenty": "$105",
    "hourlyRateSnowRemoval": "$35/hour",
    "billingScheduleSnowRemoval": "",
    "notesSnowRemoval": "",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  },
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "Residential Clients",
    "address": "1517 Triggs Ave",
    "propertyManagerName": "-",
    "lg": true,
    "isActive": true,
    "snowRemoval": false,
    "lawnCare": true,
    "scheduleLawnCare": "weekly",
    "priceLawnCareVisit": "$55",
    "email": "vicki102001@charter.net",
    "phone": "218-390-8772",
    "notesLawnCare": "",
    "salt": "",
    "triggerSnowRemoval": "",
    "billingStructureSnowRemoval": "",
    "snowRemovalZeroToFive": "",
    "snowRemovalFiveToTen": "",
    "snowRemovalTenToFifthteen": "",
    "snowRemovalFifthteenToTwenty": "",
    "hourlyRateSnowRemoval": "",
    "billingScheduleSnowRemoval": "",
    "notesSnowRemoval": "",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  },
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "Residential Clients",
    "address": "318 Winnepeg Ave",
    "propertyManagerName": "-",
    "lg": true,
    "isActive": true,
    "snowRemoval": true,
    "lawnCare": true,
    "scheduleLawnCare": "BiWeekly-Mon",
    "priceLawnCareVisit": "$15",
    "email": "Jan",
    "phone": "218-461-7326",
    "notesLawnCare": "",
    "salt": "Yes/Maybe",
    "triggerSnowRemoval": "1 inch",
    "billingStructureSnowRemoval": "Per Push",
    "snowRemovalZeroToFive": "$20",
    "snowRemovalFiveToTen": "$35",
    "snowRemovalTenToFifthteen": "$50",
    "snowRemovalFifthteenToTwenty": "$65",
    "hourlyRateSnowRemoval": "$35/hour",
    "billingScheduleSnowRemoval": "",
    "notesSnowRemoval": "",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  },
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "Residential Clients",
    "address": "414 N 18th Ave E",
    "propertyManagerName": "-",
    "lg": true,
    "isActive": true,
    "snowRemoval": false,
    "lawnCare": true,
    "scheduleLawnCare": "Weekly?",
    "priceLawnCareVisit": "$20",
    "email": "",
    "phone": "218-576-9893",
    "notesLawnCare": "",
    "salt": "",
    "triggerSnowRemoval": "",
    "billingStructureSnowRemoval": "",
    "snowRemovalZeroToFive": "",
    "snowRemovalFiveToTen": "",
    "snowRemovalTenToFifthteen": "",
    "snowRemovalFifthteenToTwenty": "",
    "hourlyRateSnowRemoval": "",
    "billingScheduleSnowRemoval": "",
    "notesSnowRemoval": "",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  },
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "Residential Clients",
    "address": "521 W 6th St",
    "propertyManagerName": "-",
    "lg": true,
    "isActive": true,
    "snowRemoval": false,
    "lawnCare": true,
    "scheduleLawnCare": "Weekly",
    "priceLawnCareVisit": "$18",
    "email": "klun2002@yahoo.com",
    "phone": "",
    "notesLawnCare": "",
    "salt": "",
    "triggerSnowRemoval": "",
    "billingStructureSnowRemoval": "",
    "snowRemovalZeroToFive": "",
    "snowRemovalFiveToTen": "",
    "snowRemovalTenToFifthteen": "",
    "snowRemovalFifthteenToTwenty": "",
    "hourlyRateSnowRemoval": "",
    "billingScheduleSnowRemoval": "",
    "notesSnowRemoval": "",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  },
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "Residential Clients",
    "address": "2515 Jefferson St.",
    "propertyManagerName": "-",
    "lg": true,
    "isActive": true,
    "snowRemoval": false,
    "lawnCare": true,
    "scheduleLawnCare": "Weekly-Mon",
    "priceLawnCareVisit": "$15",
    "email": "",
    "phone": "218-481-5730",
    "notesLawnCare": "",
    "salt": "",
    "triggerSnowRemoval": "",
    "billingStructureSnowRemoval": "",
    "snowRemovalZeroToFive": "",
    "snowRemovalFiveToTen": "",
    "snowRemovalTenToFifthteen": "",
    "snowRemovalFifthteenToTwenty": "",
    "hourlyRateSnowRemoval": "",
    "billingScheduleSnowRemoval": "",
    "notesSnowRemoval": "",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  },
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "Residential Clients",
    "address": "2715 West 8th St",
    "propertyManagerName": "Cherly Martell",
    "lg": true,
    "isActive": true,
    "snowRemoval": false,
    "lawnCare": true,
    "scheduleLawnCare": "Weekly",
    "priceLawnCareVisit": "$37",
    "email": "cherylm2018@hushmail.com",
    "phone": "",
    "notesLawnCare": "",
    "salt": "",
    "triggerSnowRemoval": "",
    "billingStructureSnowRemoval": "",
    "snowRemovalZeroToFive": "",
    "snowRemovalFiveToTen": "",
    "snowRemovalTenToFifthteen": "",
    "snowRemovalFifthteenToTwenty": "",
    "hourlyRateSnowRemoval": "",
    "billingScheduleSnowRemoval": "",
    "notesSnowRemoval": "",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  },
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "Residential Clients",
    "address": "418 Fern Ave",
    "propertyManagerName": "-",
    "lg": true,
    "isActive": true,
    "snowRemoval": false,
    "lawnCare": true,
    "scheduleLawnCare": "Biweekly",
    "priceLawnCareVisit": "$22",
    "email": "twins8257@gmail.com",
    "phone": "651-214-8980",
    "notesLawnCare": "",
    "salt": "",
    "triggerSnowRemoval": "",
    "billingStructureSnowRemoval": "",
    "snowRemovalZeroToFive": "",
    "snowRemovalFiveToTen": "",
    "snowRemovalTenToFifthteen": "",
    "snowRemovalFifthteenToTwenty": "",
    "hourlyRateSnowRemoval": "",
    "billingScheduleSnowRemoval": "",
    "notesSnowRemoval": "",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  },
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "Residential Clients",
    "address": "205 Myrtle St.",
    "propertyManagerName": "Anthony Layman",
    "lg": true,
    "isActive": true,
    "snowRemoval": true,
    "lawnCare": true,
    "scheduleLawnCare": "BiWeekly-Wed",
    "priceLawnCareVisit": "$40",
    "email": "antonyjlymn@gmail.com",
    "phone": "",
    "notesLawnCare": "",
    "salt": "Yes/Maybe",
    "triggerSnowRemoval": "1 inch",
    "billingStructureSnowRemoval": "Hourly",
    "snowRemovalZeroToFive": "",
    "snowRemovalFiveToTen": "",
    "snowRemovalTenToFifthteen": "",
    "snowRemovalFifthteenToTwenty": "",
    "hourlyRateSnowRemoval": "$40/hour",
    "billingScheduleSnowRemoval": "",
    "notesSnowRemoval": "",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  },
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "Residential Clients",
    "address": "3710 Chambersburg Ave",
    "propertyManagerName": "-",
    "lg": true,
    "isActive": true,
    "snowRemoval": false,
    "lawnCare": true,
    "scheduleLawnCare": "Weekly",
    "priceLawnCareVisit": "$25",
    "email": "",
    "phone": "218-390-3272",
    "notesLawnCare": "",
    "salt": "",
    "triggerSnowRemoval": "",
    "billingStructureSnowRemoval": "",
    "snowRemovalZeroToFive": "",
    "snowRemovalFiveToTen": "",
    "snowRemovalTenToFifthteen": "",
    "snowRemovalFifthteenToTwenty": "",
    "hourlyRateSnowRemoval": "",
    "billingScheduleSnowRemoval": "",
    "notesSnowRemoval": "",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  },
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "Residential Clients",
    "address": "1433 N 7th Ave",
    "propertyManagerName": "-",
    "lg": true,
    "isActive": true,
    "snowRemoval": false,
    "lawnCare": true,
    "scheduleLawnCare": "BiWeekly",
    "priceLawnCareVisit": "$28",
    "email": "abromen@gmail.com",
    "phone": "218-340-5324",
    "notesLawnCare": "",
    "salt": "",
    "triggerSnowRemoval": "",
    "billingStructureSnowRemoval": "",
    "snowRemovalZeroToFive": "",
    "snowRemovalFiveToTen": "",
    "snowRemovalTenToFifthteen": "",
    "snowRemovalFifthteenToTwenty": "",
    "hourlyRateSnowRemoval": "",
    "billingScheduleSnowRemoval": "",
    "notesSnowRemoval": "",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  },
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "Residential Clients",
    "address": "5118 Glenwood St.",
    "propertyManagerName": "Paul",
    "lg": true,
    "isActive": true,
    "snowRemoval": true,
    "lawnCare": true,
    "scheduleLawnCare": "Weekly",
    "priceLawnCareVisit": "$30",
    "email": "paul.enenbach@gmail.com",
    "phone": "715-347-8816",
    "notesLawnCare": "",
    "salt": "Yes/Maybe",
    "triggerSnowRemoval": "4 inches",
    "billingStructureSnowRemoval": "Per Push",
    "snowRemovalZeroToFive": "$45",
    "snowRemovalFiveToTen": "$65",
    "snowRemovalTenToFifthteen": "$85",
    "snowRemovalFifthteenToTwenty": "$105",
    "hourlyRateSnowRemoval": "$35/hour",
    "billingScheduleSnowRemoval": "",
    "notesSnowRemoval": "",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  },
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "Residential Clients",
    "address": "414 Sparkman Ave",
    "propertyManagerName": "-",
    "lg": true,
    "isActive": true,
    "snowRemoval": false,
    "lawnCare": true,
    "scheduleLawnCare": "Weekly",
    "priceLawnCareVisit": "$30",
    "email": "",
    "phone": "218-393-3057",
    "notesLawnCare": "",
    "salt": "",
    "triggerSnowRemoval": "",
    "billingStructureSnowRemoval": "",
    "snowRemovalZeroToFive": "",
    "snowRemovalFiveToTen": "",
    "snowRemovalTenToFifthteen": "",
    "snowRemovalFifthteenToTwenty": "",
    "hourlyRateSnowRemoval": "",
    "billingScheduleSnowRemoval": "",
    "notesSnowRemoval": "",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  },
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "Residential Clients",
    "address": "3714 Chambersburg Ave",
    "propertyManagerName": "Marlys F Anderson",
    "lg": true,
    "isActive": true,
    "snowRemoval": false,
    "lawnCare": true,
    "scheduleLawnCare": "Weekly",
    "priceLawnCareVisit": "$50",
    "email": "marlysandrsn@aol.com",
    "phone": "218-727-3089",
    "notesLawnCare": "",
    "salt": "",
    "triggerSnowRemoval": "",
    "billingStructureSnowRemoval": "",
    "snowRemovalZeroToFive": "",
    "snowRemovalFiveToTen": "",
    "snowRemovalTenToFifthteen": "",
    "snowRemovalFifthteenToTwenty": "",
    "hourlyRateSnowRemoval": "",
    "billingScheduleSnowRemoval": "",
    "notesSnowRemoval": "",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  },
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "Residential Clients",
    "address": "5566 Fish Lake Dam rd.",
    "propertyManagerName": "-",
    "lg": true,
    "isActive": true,
    "snowRemoval": false,
    "lawnCare": true,
    "scheduleLawnCare": "Biweekly",
    "priceLawnCareVisit": "$50",
    "email": "kschatts@gmail.com",
    "phone": "",
    "notesLawnCare": "",
    "salt": "",
    "triggerSnowRemoval": "",
    "billingStructureSnowRemoval": "",
    "snowRemovalZeroToFive": "",
    "snowRemovalFiveToTen": "",
    "snowRemovalTenToFifthteen": "",
    "snowRemovalFifthteenToTwenty": "",
    "hourlyRateSnowRemoval": "",
    "billingScheduleSnowRemoval": "",
    "notesSnowRemoval": "",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  },
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "Residential Clients",
    "address": "2234 Waverly Ave",
    "propertyManagerName": "Steve Lichterman",
    "lg": true,
    "isActive": true,
    "snowRemoval": false,
    "lawnCare": true,
    "scheduleLawnCare": "Weekly",
    "priceLawnCareVisit": "$60",
    "email": "",
    "phone": "218-940-1007",
    "notesLawnCare": "",
    "salt": "",
    "triggerSnowRemoval": "",
    "billingStructureSnowRemoval": "",
    "snowRemovalZeroToFive": "",
    "snowRemovalFiveToTen": "",
    "snowRemovalTenToFifthteen": "",
    "snowRemovalFifthteenToTwenty": "",
    "hourlyRateSnowRemoval": "",
    "billingScheduleSnowRemoval": "",
    "notesSnowRemoval": "",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  },
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "Residential Clients",
    "address": "4128 Decker Rd",
    "propertyManagerName": "Sam Farago",
    "lg": true,
    "isActive": true,
    "snowRemoval": false,
    "lawnCare": true,
    "scheduleLawnCare": "Weekly",
    "priceLawnCareVisit": "$60",
    "email": "",
    "phone": "218-428-3634",
    "notesLawnCare": "",
    "salt": "",
    "triggerSnowRemoval": "",
    "billingStructureSnowRemoval": "",
    "snowRemovalZeroToFive": "",
    "snowRemovalFiveToTen": "",
    "snowRemovalTenToFifthteen": "",
    "snowRemovalFifthteenToTwenty": "",
    "hourlyRateSnowRemoval": "",
    "billingScheduleSnowRemoval": "",
    "notesSnowRemoval": "",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  },
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "Residential Clients",
    "address": "2034 Minnesota Ave",
    "propertyManagerName": "John Soderstrom",
    "lg": true,
    "isActive": true,
    "snowRemoval": false,
    "lawnCare": true,
    "scheduleLawnCare": "Weekly",
    "priceLawnCareVisit": "$50",
    "email": "",
    "phone": "218-248-7886",
    "notesLawnCare": "Mow back biweekly charge $25/front, $25/back",
    "salt": "",
    "triggerSnowRemoval": "",
    "billingStructureSnowRemoval": "",
    "snowRemovalZeroToFive": "",
    "snowRemovalFiveToTen": "",
    "snowRemovalTenToFifthteen": "",
    "snowRemovalFifthteenToTwenty": "",
    "hourlyRateSnowRemoval": "",
    "billingScheduleSnowRemoval": "",
    "notesSnowRemoval": "",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  },
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "CMRA",
    "address": "1405/1307 Miller Trunk Hwy",
    "propertyManagerName": "-",
    "lg": true,
    "isActive": true,
    "snowRemoval": false,
    "lawnCare": true,
    "scheduleLawnCare": "Weekly",
    "priceLawnCareVisit": "$132.50",
    "email": "beth@cmrasells.com",
    "phone": "(218) 727-0064",
    "notesLawnCare": "",
    "salt": "",
    "triggerSnowRemoval": "",
    "billingStructureSnowRemoval": "",
    "snowRemovalZeroToFive": "",
    "snowRemovalFiveToTen": "",
    "snowRemovalTenToFifthteen": "",
    "snowRemovalFifthteenToTwenty": "",
    "hourlyRateSnowRemoval": "",
    "billingScheduleSnowRemoval": "",
    "notesSnowRemoval": "",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  },
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "CMRA",
    "address": "4310 Menards Dr.",
    "propertyManagerName": "-",
    "lg": true,
    "isActive": true,
    "snowRemoval": false,
    "lawnCare": true,
    "scheduleLawnCare": "Weekly",
    "priceLawnCareVisit": "$42",
    "email": "beth@cmrasells.com",
    "phone": "(218) 727-0065",
    "notesLawnCare": "",
    "salt": "",
    "triggerSnowRemoval": "",
    "billingStructureSnowRemoval": "",
    "snowRemovalZeroToFive": "",
    "snowRemovalFiveToTen": "",
    "snowRemovalTenToFifthteen": "",
    "snowRemovalFifthteenToTwenty": "",
    "hourlyRateSnowRemoval": "",
    "billingScheduleSnowRemoval": "",
    "notesSnowRemoval": "",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  },
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "CMRA",
    "address": "1131 E 4th St.",
    "propertyManagerName": "-",
    "lg": true,
    "isActive": true,
    "snowRemoval": false,
    "lawnCare": true,
    "scheduleLawnCare": "Weekly",
    "priceLawnCareVisit": "$15",
    "email": "beth@cmrasells.com",
    "phone": "(218) 727-0066",
    "notesLawnCare": "",
    "salt": "",
    "triggerSnowRemoval": "",
    "billingStructureSnowRemoval": "",
    "snowRemovalZeroToFive": "",
    "snowRemovalFiveToTen": "",
    "snowRemovalTenToFifthteen": "",
    "snowRemovalFifthteenToTwenty": "",
    "hourlyRateSnowRemoval": "",
    "billingScheduleSnowRemoval": "",
    "notesSnowRemoval": "",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  },
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "CMRA",
    "address": "701-711 E 4th St.",
    "propertyManagerName": "-",
    "lg": true,
    "isActive": true,
    "snowRemoval": false,
    "lawnCare": true,
    "scheduleLawnCare": "Weekly",
    "priceLawnCareVisit": "$80",
    "email": "beth@cmrasells.com",
    "phone": "(218) 727-0067",
    "notesLawnCare": "",
    "salt": "",
    "triggerSnowRemoval": "",
    "billingStructureSnowRemoval": "",
    "snowRemovalZeroToFive": "",
    "snowRemovalFiveToTen": "",
    "snowRemovalTenToFifthteen": "",
    "snowRemovalFifthteenToTwenty": "",
    "hourlyRateSnowRemoval": "",
    "billingScheduleSnowRemoval": "",
    "notesSnowRemoval": "",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  },
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "CMRA",
    "address": "908 E Skyline Pkwy",
    "propertyManagerName": "-",
    "lg": true,
    "isActive": true,
    "snowRemoval": false,
    "lawnCare": true,
    "scheduleLawnCare": "weekly",
    "priceLawnCareVisit": "$30",
    "email": "beth@cmrasells.com",
    "phone": "(218) 727-0068",
    "notesLawnCare": "",
    "salt": "",
    "triggerSnowRemoval": "",
    "billingStructureSnowRemoval": "",
    "snowRemovalZeroToFive": "",
    "snowRemovalFiveToTen": "",
    "snowRemovalTenToFifthteen": "",
    "snowRemovalFifthteenToTwenty": "",
    "hourlyRateSnowRemoval": "",
    "billingScheduleSnowRemoval": "",
    "notesSnowRemoval": "",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  },
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "Messina: Invioce 1",
    "address": "421 N 18th Ave E",
    "propertyManagerName": "-",
    "lg": true,
    "isActive": true,
    "snowRemoval": false,
    "lawnCare": true,
    "scheduleLawnCare": "Weekly",
    "priceLawnCareVisit": "$21",
    "email": "debmessina@charter.net",
    "phone": "218-391-8755",
    "notesLawnCare": "",
    "salt": "",
    "triggerSnowRemoval": "",
    "billingStructureSnowRemoval": "",
    "snowRemovalZeroToFive": "",
    "snowRemovalFiveToTen": "",
    "snowRemovalTenToFifthteen": "",
    "snowRemovalFifthteenToTwenty": "",
    "hourlyRateSnowRemoval": "",
    "billingScheduleSnowRemoval": "",
    "notesSnowRemoval": "",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  },
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "Messina: Invioce 1",
    "address": "1513 Jefferson St.",
    "propertyManagerName": "-",
    "lg": true,
    "isActive": true,
    "snowRemoval": false,
    "lawnCare": true,
    "scheduleLawnCare": "Weekly",
    "priceLawnCareVisit": "$21",
    "email": "debmessina@charter.net",
    "phone": "218-391-8756",
    "notesLawnCare": "",
    "salt": "",
    "triggerSnowRemoval": "",
    "billingStructureSnowRemoval": "",
    "snowRemovalZeroToFive": "",
    "snowRemovalFiveToTen": "",
    "snowRemovalTenToFifthteen": "",
    "snowRemovalFifthteenToTwenty": "",
    "hourlyRateSnowRemoval": "",
    "billingScheduleSnowRemoval": "",
    "notesSnowRemoval": "",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  },
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "Messina: Invioce 2",
    "address": "114-112 S 14th Ave E",
    "propertyManagerName": "-",
    "lg": true,
    "isActive": true,
    "snowRemoval": false,
    "lawnCare": true,
    "scheduleLawnCare": "Weekly",
    "priceLawnCareVisit": "$21",
    "email": "debmessina@charter.net",
    "phone": "218-391-8757",
    "notesLawnCare": "",
    "salt": "",
    "triggerSnowRemoval": "",
    "billingStructureSnowRemoval": "",
    "snowRemovalZeroToFive": "",
    "snowRemovalFiveToTen": "",
    "snowRemovalTenToFifthteen": "",
    "snowRemovalFifthteenToTwenty": "",
    "hourlyRateSnowRemoval": "",
    "billingScheduleSnowRemoval": "",
    "notesSnowRemoval": "",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  },
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "Messina: Invioce 2",
    "address": "920 E 5th St.",
    "propertyManagerName": "-",
    "lg": true,
    "isActive": true,
    "snowRemoval": false,
    "lawnCare": true,
    "scheduleLawnCare": "Weekly",
    "priceLawnCareVisit": "$21",
    "email": "debmessina@charter.net",
    "phone": "218-391-8758",
    "notesLawnCare": "",
    "salt": "",
    "triggerSnowRemoval": "",
    "billingStructureSnowRemoval": "",
    "snowRemovalZeroToFive": "",
    "snowRemovalFiveToTen": "",
    "snowRemovalTenToFifthteen": "",
    "snowRemovalFifthteenToTwenty": "",
    "hourlyRateSnowRemoval": "",
    "billingScheduleSnowRemoval": "",
    "notesSnowRemoval": "",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  },
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "Messina: Invioce 2",
    "address": "1414 Jefferson St.",
    "propertyManagerName": "-",
    "lg": true,
    "isActive": true,
    "snowRemoval": false,
    "lawnCare": true,
    "scheduleLawnCare": "Weekly",
    "priceLawnCareVisit": "$21",
    "email": "debmessina@charter.net",
    "phone": "218-391-8759",
    "notesLawnCare": "",
    "salt": "",
    "triggerSnowRemoval": "",
    "billingStructureSnowRemoval": "",
    "snowRemovalZeroToFive": "",
    "snowRemovalFiveToTen": "",
    "snowRemovalTenToFifthteen": "",
    "snowRemovalFifthteenToTwenty": "",
    "hourlyRateSnowRemoval": "",
    "billingScheduleSnowRemoval": "",
    "notesSnowRemoval": "",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  },
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "Messina: Invioce 2",
    "address": "1511-13 E 2nd St.",
    "propertyManagerName": "-",
    "lg": true,
    "isActive": true,
    "snowRemoval": false,
    "lawnCare": true,
    "scheduleLawnCare": "Weekly",
    "priceLawnCareVisit": "$21",
    "email": "debmessina@charter.net",
    "phone": "218-391-8760",
    "notesLawnCare": "",
    "salt": "",
    "triggerSnowRemoval": "",
    "billingStructureSnowRemoval": "",
    "snowRemovalZeroToFive": "",
    "snowRemovalFiveToTen": "",
    "snowRemovalTenToFifthteen": "",
    "snowRemovalFifthteenToTwenty": "",
    "hourlyRateSnowRemoval": "",
    "billingScheduleSnowRemoval": "",
    "notesSnowRemoval": "",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  },
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "Messina: Invioce 2",
    "address": "1719 E 5th St.",
    "propertyManagerName": "-",
    "lg": true,
    "isActive": true,
    "snowRemoval": false,
    "lawnCare": true,
    "scheduleLawnCare": "Weekly",
    "priceLawnCareVisit": "$35",
    "email": "debmessina@charter.net",
    "phone": "218-391-8761",
    "notesLawnCare": "",
    "salt": "",
    "triggerSnowRemoval": "",
    "billingStructureSnowRemoval": "",
    "snowRemovalZeroToFive": "",
    "snowRemovalFiveToTen": "",
    "snowRemovalTenToFifthteen": "",
    "snowRemovalFifthteenToTwenty": "",
    "hourlyRateSnowRemoval": "",
    "billingScheduleSnowRemoval": "",
    "notesSnowRemoval": "",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  },
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "Messina: Invioce 3",
    "address": "1512 E Superior St.",
    "propertyManagerName": "-",
    "lg": true,
    "isActive": true,
    "snowRemoval": false,
    "lawnCare": true,
    "scheduleLawnCare": "Weekly",
    "priceLawnCareVisit": "$10.50",
    "email": "debmessina@charter.net",
    "phone": "218-391-8762",
    "notesLawnCare": "",
    "salt": "",
    "triggerSnowRemoval": "",
    "billingStructureSnowRemoval": "",
    "snowRemovalZeroToFive": "",
    "snowRemovalFiveToTen": "",
    "snowRemovalTenToFifthteen": "",
    "snowRemovalFifthteenToTwenty": "",
    "hourlyRateSnowRemoval": "",
    "billingScheduleSnowRemoval": "",
    "notesSnowRemoval": "",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  },
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "Messina: Invioce 4",
    "address": "418 S 23rd Ave E",
    "propertyManagerName": "-",
    "lg": true,
    "isActive": true,
    "snowRemoval": false,
    "lawnCare": true,
    "scheduleLawnCare": "Weekly",
    "priceLawnCareVisit": "$30",
    "email": "debmessina@charter.net",
    "phone": "218-391-8763",
    "notesLawnCare": "",
    "salt": "",
    "triggerSnowRemoval": "",
    "billingStructureSnowRemoval": "",
    "snowRemovalZeroToFive": "",
    "snowRemovalFiveToTen": "",
    "snowRemovalTenToFifthteen": "",
    "snowRemovalFifthteenToTwenty": "",
    "hourlyRateSnowRemoval": "",
    "billingScheduleSnowRemoval": "",
    "notesSnowRemoval": "",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  },
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "Messina: Invioce 4",
    "address": "1527 E 2nd St.",
    "propertyManagerName": "-",
    "lg": true,
    "isActive": true,
    "snowRemoval": false,
    "lawnCare": true,
    "scheduleLawnCare": "Weekly",
    "priceLawnCareVisit": "$22",
    "email": "debmessina@charter.net",
    "phone": "218-391-8764",
    "notesLawnCare": "",
    "salt": "",
    "triggerSnowRemoval": "",
    "billingStructureSnowRemoval": "",
    "snowRemovalZeroToFive": "",
    "snowRemovalFiveToTen": "",
    "snowRemovalTenToFifthteen": "",
    "snowRemovalFifthteenToTwenty": "",
    "hourlyRateSnowRemoval": "",
    "billingScheduleSnowRemoval": "",
    "notesSnowRemoval": "",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  },
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "Messina: Invioce 4",
    "address": "1620 E 3rd St.",
    "propertyManagerName": "-",
    "lg": true,
    "isActive": true,
    "snowRemoval": false,
    "lawnCare": true,
    "scheduleLawnCare": "Weekly",
    "priceLawnCareVisit": "$35",
    "email": "debmessina@charter.net",
    "phone": "218-391-8765",
    "notesLawnCare": "",
    "salt": "",
    "triggerSnowRemoval": "",
    "billingStructureSnowRemoval": "",
    "snowRemovalZeroToFive": "",
    "snowRemovalFiveToTen": "",
    "snowRemovalTenToFifthteen": "",
    "snowRemovalFifthteenToTwenty": "",
    "hourlyRateSnowRemoval": "",
    "billingScheduleSnowRemoval": "",
    "notesSnowRemoval": "",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  },
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "Adam",
    "address": "607 Grand Ave",
    "propertyManagerName": "-",
    "lg": false,
    "isActive": true,
    "snowRemoval": false,
    "lawnCare": true,
    "scheduleLawnCare": "BiWeekly-Sat",
    "priceLawnCareVisit": "$22",
    "email": "",
    "phone": "715-817-3917",
    "notesLawnCare": "",
    "salt": "",
    "triggerSnowRemoval": "",
    "billingStructureSnowRemoval": "",
    "snowRemovalZeroToFive": "",
    "snowRemovalFiveToTen": "",
    "snowRemovalTenToFifthteen": "",
    "snowRemovalFifthteenToTwenty": "",
    "hourlyRateSnowRemoval": "",
    "billingScheduleSnowRemoval": "",
    "notesSnowRemoval": "",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  },
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "Adam",
    "address": "1708 N 17th",
    "propertyManagerName": "-",
    "lg": false,
    "isActive": true,
    "snowRemoval": false,
    "lawnCare": true,
    "scheduleLawnCare": "BiWeekly",
    "priceLawnCareVisit": "$16",
    "email": "",
    "phone": "715-817-3918",
    "notesLawnCare": "",
    "salt": "",
    "triggerSnowRemoval": "",
    "billingStructureSnowRemoval": "",
    "snowRemovalZeroToFive": "",
    "snowRemovalFiveToTen": "",
    "snowRemovalTenToFifthteen": "",
    "snowRemovalFifthteenToTwenty": "",
    "hourlyRateSnowRemoval": "",
    "billingScheduleSnowRemoval": "",
    "notesSnowRemoval": "",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  },
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "Adam",
    "address": "1101 Hammond Ave",
    "propertyManagerName": "-",
    "lg": false,
    "isActive": true,
    "snowRemoval": false,
    "lawnCare": true,
    "scheduleLawnCare": "BiWeekly",
    "priceLawnCareVisit": "$30",
    "email": "",
    "phone": "715-817-3919",
    "notesLawnCare": "",
    "salt": "",
    "triggerSnowRemoval": "",
    "billingStructureSnowRemoval": "",
    "snowRemovalZeroToFive": "",
    "snowRemovalFiveToTen": "",
    "snowRemovalTenToFifthteen": "",
    "snowRemovalFifthteenToTwenty": "",
    "hourlyRateSnowRemoval": "",
    "billingScheduleSnowRemoval": "",
    "notesSnowRemoval": "",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  },
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "Adam",
    "address": "111 N 26th Ave W",
    "propertyManagerName": "-",
    "lg": false,
    "isActive": true,
    "snowRemoval": false,
    "lawnCare": true,
    "scheduleLawnCare": "BiWeekly",
    "priceLawnCareVisit": "$17",
    "email": "",
    "phone": "715-817-3920",
    "notesLawnCare": "",
    "salt": "",
    "triggerSnowRemoval": "",
    "billingStructureSnowRemoval": "",
    "snowRemovalZeroToFive": "",
    "snowRemovalFiveToTen": "",
    "snowRemovalTenToFifthteen": "",
    "snowRemovalFifthteenToTwenty": "",
    "hourlyRateSnowRemoval": "",
    "billingScheduleSnowRemoval": "",
    "notesSnowRemoval": "",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  },
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "Adam",
    "address": "120 N 25th Ave W",
    "propertyManagerName": "-",
    "lg": false,
    "isActive": true,
    "snowRemoval": false,
    "lawnCare": true,
    "scheduleLawnCare": "BiWeekly",
    "priceLawnCareVisit": "$12",
    "email": "",
    "phone": "715-817-3921",
    "notesLawnCare": "",
    "salt": "",
    "triggerSnowRemoval": "",
    "billingStructureSnowRemoval": "",
    "snowRemovalZeroToFive": "",
    "snowRemovalFiveToTen": "",
    "snowRemovalTenToFifthteen": "",
    "snowRemovalFifthteenToTwenty": "",
    "hourlyRateSnowRemoval": "",
    "billingScheduleSnowRemoval": "",
    "notesSnowRemoval": "",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  },
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "Adam",
    "address": "2422 W 4th St",
    "propertyManagerName": "-",
    "lg": false,
    "isActive": true,
    "snowRemoval": false,
    "lawnCare": true,
    "scheduleLawnCare": "BiWeekly",
    "priceLawnCareVisit": "$14",
    "email": "",
    "phone": "715-817-3922",
    "notesLawnCare": "",
    "salt": "",
    "triggerSnowRemoval": "",
    "billingStructureSnowRemoval": "",
    "snowRemovalZeroToFive": "",
    "snowRemovalFiveToTen": "",
    "snowRemovalTenToFifthteen": "",
    "snowRemovalFifthteenToTwenty": "",
    "hourlyRateSnowRemoval": "",
    "billingScheduleSnowRemoval": "",
    "notesSnowRemoval": "",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  },
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "Adam",
    "address": "1317 N 101st Ave W",
    "propertyManagerName": "-",
    "lg": false,
    "isActive": true,
    "snowRemoval": false,
    "lawnCare": true,
    "scheduleLawnCare": "BiWeekly",
    "priceLawnCareVisit": "$20",
    "email": "",
    "phone": "715-817-3923",
    "notesLawnCare": "",
    "salt": "",
    "triggerSnowRemoval": "",
    "billingStructureSnowRemoval": "",
    "snowRemovalZeroToFive": "",
    "snowRemovalFiveToTen": "",
    "snowRemovalTenToFifthteen": "",
    "snowRemovalFifthteenToTwenty": "",
    "hourlyRateSnowRemoval": "",
    "billingScheduleSnowRemoval": "",
    "notesSnowRemoval": "",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  },
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "Adam",
    "address": "1205 Weeks Ave",
    "propertyManagerName": "-",
    "lg": false,
    "isActive": true,
    "snowRemoval": false,
    "lawnCare": true,
    "scheduleLawnCare": "BiWeekly",
    "priceLawnCareVisit": "$26",
    "email": "",
    "phone": "715-817-3924",
    "notesLawnCare": "",
    "salt": "",
    "triggerSnowRemoval": "",
    "billingStructureSnowRemoval": "",
    "snowRemovalZeroToFive": "",
    "snowRemovalFiveToTen": "",
    "snowRemovalTenToFifthteen": "",
    "snowRemovalFifthteenToTwenty": "",
    "hourlyRateSnowRemoval": "",
    "billingScheduleSnowRemoval": "",
    "notesSnowRemoval": "",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  },
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "Gregg",
    "address": "",
    "propertyManagerName": "-",
    "lg": false,
    "isActive": true,
    "snowRemoval": false,
    "lawnCare": true,
    "scheduleLawnCare": "BiWeekly-Thur",
    "priceLawnCareVisit": "$21",
    "email": "",
    "phone": "218-9690219",
    "notesLawnCare": "",
    "salt": "",
    "triggerSnowRemoval": "",
    "billingStructureSnowRemoval": "",
    "snowRemovalZeroToFive": "",
    "snowRemovalFiveToTen": "",
    "snowRemovalTenToFifthteen": "",
    "snowRemovalFifthteenToTwenty": "",
    "hourlyRateSnowRemoval": "",
    "billingScheduleSnowRemoval": "",
    "notesSnowRemoval": "",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  },
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "Residential Clients",
    "address": "2113 E 2nd St.",
    "propertyManagerName": "Maggie",
    "lg": true,
    "isActive": true,
    "snowRemoval": true,
    "lawnCare": false,
    "scheduleLawnCare": "",
    "priceLawnCareVisit": "",
    "email": "",
    "phone": "218-838-8822, 218724-4666",
    "notesLawnCare": "holmen.rhonda@gmail.com",
    "salt": "",
    "triggerSnowRemoval": "4 inches",
    "billingStructureSnowRemoval": "Per Push",
    "snowRemovalZeroToFive": "$40",
    "snowRemovalFiveToTen": "$60",
    "snowRemovalTenToFifthteen": "$80",
    "snowRemovalFifthteenToTwenty": "$100",
    "hourlyRateSnowRemoval": "$35/hour",
    "billingScheduleSnowRemoval": "",
    "notesSnowRemoval": "Bill Ronda Holmen",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  },
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "Residential Clients",
    "address": "3202 Ewing Ave",
    "propertyManagerName": "Marylin Minter",
    "lg": true,
    "isActive": true,
    "snowRemoval": true,
    "lawnCare": false,
    "scheduleLawnCare": "",
    "priceLawnCareVisit": "",
    "email": "",
    "phone": "218-724-9446",
    "notesLawnCare": "",
    "salt": "",
    "triggerSnowRemoval": "1 inch",
    "billingStructureSnowRemoval": "Per Push",
    "snowRemovalZeroToFive": "$40-$60",
    "snowRemovalFiveToTen": "$80",
    "snowRemovalTenToFifthteen": "$100",
    "snowRemovalFifthteenToTwenty": "$120",
    "hourlyRateSnowRemoval": "$35/hour",
    "billingScheduleSnowRemoval": "",
    "notesSnowRemoval": "",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  },
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "Residential Clients",
    "address": "2824 Snowy Owl Circle",
    "propertyManagerName": "Ronda Holmen",
    "lg": true,
    "isActive": true,
    "snowRemoval": true,
    "lawnCare": false,
    "scheduleLawnCare": "",
    "priceLawnCareVisit": "",
    "email": "",
    "phone": "218-626-5937",
    "notesLawnCare": "holmen.rhonda@gmail.com",
    "salt": "Yes",
    "triggerSnowRemoval": "1 inch",
    "billingStructureSnowRemoval": "Per Push",
    "snowRemovalZeroToFive": "$35-$65",
    "snowRemovalFiveToTen": "$85",
    "snowRemovalTenToFifthteen": "$105",
    "snowRemovalFifthteenToTwenty": "$125",
    "hourlyRateSnowRemoval": "$35/hour",
    "billingScheduleSnowRemoval": "",
    "notesSnowRemoval": "",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  },
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "Residential Clients",
    "address": "303 Ridgewood St.",
    "propertyManagerName": "",
    "lg": true,
    "isActive": true,
    "snowRemoval": true,
    "lawnCare": false,
    "scheduleLawnCare": "",
    "priceLawnCareVisit": "",
    "email": "",
    "phone": "406-581-2619",
    "notesLawnCare": "",
    "salt": "Yes/Maybe",
    "triggerSnowRemoval": "On Call",
    "billingStructureSnowRemoval": "Per Push",
    "snowRemovalZeroToFive": "$80",
    "snowRemovalFiveToTen": "$105",
    "snowRemovalTenToFifthteen": "$130",
    "snowRemovalFifthteenToTwenty": "$155",
    "hourlyRateSnowRemoval": "$40/hour",
    "billingScheduleSnowRemoval": "",
    "notesSnowRemoval": "",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  },
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "Residential Clients",
    "address": "5811 Glenwood St.",
    "propertyManagerName": "Chuckie",
    "lg": true,
    "isActive": true,
    "snowRemoval": true,
    "lawnCare": false,
    "scheduleLawnCare": "",
    "priceLawnCareVisit": "",
    "email": "",
    "phone": "218-393-3192",
    "notesLawnCare": "",
    "salt": "Yes/Maybe",
    "triggerSnowRemoval": "1 inch",
    "billingStructureSnowRemoval": "Per Push",
    "snowRemovalZeroToFive": "$20-$35",
    "snowRemovalFiveToTen": "$50",
    "snowRemovalTenToFifthteen": "$65",
    "snowRemovalFifthteenToTwenty": "$80",
    "hourlyRateSnowRemoval": "$35/hour",
    "billingScheduleSnowRemoval": "",
    "notesSnowRemoval": "",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  },
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "Residential Clients",
    "address": "3133 E Superior St.",
    "propertyManagerName": "Nancy Schwert",
    "lg": true,
    "isActive": true,
    "snowRemoval": true,
    "lawnCare": false,
    "scheduleLawnCare": "",
    "priceLawnCareVisit": "",
    "email": "",
    "phone": "218-348-1961",
    "notesLawnCare": "nancy.schwerdt@gmail.com",
    "salt": "Yes/Maybe",
    "triggerSnowRemoval": "1 inch?",
    "billingStructureSnowRemoval": "Per Push",
    "snowRemovalZeroToFive": "$70",
    "snowRemovalFiveToTen": "$95",
    "snowRemovalTenToFifthteen": "$120",
    "snowRemovalFifthteenToTwenty": "$145",
    "hourlyRateSnowRemoval": "$35/hour",
    "billingScheduleSnowRemoval": "",
    "notesSnowRemoval": "",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  },
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "Residential Clients",
    "address": "2105 Jefferson St.",
    "propertyManagerName": "Kurt Haubrich",
    "lg": true,
    "isActive": true,
    "snowRemoval": true,
    "lawnCare": false,
    "scheduleLawnCare": "",
    "priceLawnCareVisit": "",
    "email": "",
    "phone": "",
    "notesLawnCare": "kphaubrich@gmail.com",
    "salt": "Yes/Maybe",
    "triggerSnowRemoval": "1 inch?",
    "billingStructureSnowRemoval": "Monthly",
    "snowRemovalZeroToFive": "150/month",
    "snowRemovalFiveToTen": "",
    "snowRemovalTenToFifthteen": "",
    "snowRemovalFifthteenToTwenty": "",
    "hourlyRateSnowRemoval": "",
    "billingScheduleSnowRemoval": "Monthly",
    "notesSnowRemoval": "",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  },
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "Residential Clients",
    "address": "34 Minneapolis Ave",
    "propertyManagerName": "Tom Jamar",
    "lg": true,
    "isActive": true,
    "snowRemoval": true,
    "lawnCare": false,
    "scheduleLawnCare": "",
    "priceLawnCareVisit": "",
    "email": "",
    "phone": "",
    "notesLawnCare": "",
    "salt": "Yes/Maybe",
    "triggerSnowRemoval": "1 inch",
    "billingStructureSnowRemoval": "Hourly",
    "snowRemovalZeroToFive": "",
    "snowRemovalFiveToTen": "",
    "snowRemovalTenToFifthteen": "",
    "snowRemovalFifthteenToTwenty": "",
    "hourlyRateSnowRemoval": "$35/hour",
    "billingScheduleSnowRemoval": "",
    "notesSnowRemoval": "",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  },
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "Residential Clients",
    "address": "111 E 7th St.",
    "propertyManagerName": "Mike Steffes",
    "lg": true,
    "isActive": true,
    "snowRemoval": true,
    "lawnCare": false,
    "scheduleLawnCare": "",
    "priceLawnCareVisit": "",
    "email": "",
    "phone": "651-341-8076",
    "notesLawnCare": "Msteffes88@gmail.com",
    "salt": "Yes/Maybe",
    "triggerSnowRemoval": "3 Inches",
    "billingStructureSnowRemoval": "Per Push",
    "snowRemovalZeroToFive": "$50",
    "snowRemovalFiveToTen": "$65",
    "snowRemovalTenToFifthteen": "$80",
    "snowRemovalFifthteenToTwenty": "$95",
    "hourlyRateSnowRemoval": "$35/hour",
    "billingScheduleSnowRemoval": "",
    "notesSnowRemoval": "",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  },
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "Residential Clients",
    "address": "1010 W 3rd",
    "propertyManagerName": "Mike Steffes",
    "lg": true,
    "isActive": true,
    "snowRemoval": true,
    "lawnCare": false,
    "scheduleLawnCare": "",
    "priceLawnCareVisit": "",
    "email": "",
    "phone": "651-341-8077",
    "notesLawnCare": "Msteffes88@gmail.com",
    "salt": "Yes/Maybe",
    "triggerSnowRemoval": "3 Inches",
    "billingStructureSnowRemoval": "Per Push",
    "snowRemovalZeroToFive": "$35",
    "snowRemovalFiveToTen": "$50",
    "snowRemovalTenToFifthteen": "$65",
    "snowRemovalFifthteenToTwenty": "$80",
    "hourlyRateSnowRemoval": "$35/hour",
    "billingScheduleSnowRemoval": "",
    "notesSnowRemoval": "",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  },
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "Residential Clients",
    "address": "38 Minneapolis Ave",
    "propertyManagerName": "",
    "lg": true,
    "isActive": true,
    "snowRemoval": true,
    "lawnCare": false,
    "scheduleLawnCare": "",
    "priceLawnCareVisit": "",
    "email": "",
    "phone": "",
    "notesLawnCare": "",
    "salt": "Yes/Maybe",
    "triggerSnowRemoval": "1 inch",
    "billingStructureSnowRemoval": "Per Push",
    "snowRemovalZeroToFive": "",
    "snowRemovalFiveToTen": "",
    "snowRemovalTenToFifthteen": "",
    "snowRemovalFifthteenToTwenty": "",
    "hourlyRateSnowRemoval": "",
    "billingScheduleSnowRemoval": "",
    "notesSnowRemoval": "",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  },
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "Comercial",
    "address": "1131 E 9th St.",
    "propertyManagerName": "Mandy",
    "lg": true,
    "isActive": true,
    "snowRemoval": true,
    "lawnCare": false,
    "scheduleLawnCare": "",
    "priceLawnCareVisit": "",
    "email": "",
    "phone": "218-940-3431",
    "notesLawnCare": "",
    "salt": "Yes/Maybe",
    "triggerSnowRemoval": "1 inch",
    "billingStructureSnowRemoval": "Hourly",
    "snowRemovalZeroToFive": "",
    "snowRemovalFiveToTen": "",
    "snowRemovalTenToFifthteen": "",
    "snowRemovalFifthteenToTwenty": "",
    "hourlyRateSnowRemoval": "$40/hour",
    "billingScheduleSnowRemoval": "Bi-Weekly",
    "notesSnowRemoval": "",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  },
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "Comercial",
    "address": "4880 Miller Trk",
    "propertyManagerName": "ATK",
    "lg": true,
    "isActive": true,
    "snowRemoval": true,
    "lawnCare": false,
    "scheduleLawnCare": "",
    "priceLawnCareVisit": "",
    "email": "",
    "phone": "",
    "notesLawnCare": "",
    "salt": "Yes/Maybe",
    "triggerSnowRemoval": "1 inch",
    "billingStructureSnowRemoval": "Per Push",
    "snowRemovalZeroToFive": "$260",
    "snowRemovalFiveToTen": "$260",
    "snowRemovalTenToFifthteen": "$520",
    "snowRemovalFifthteenToTwenty": "$520",
    "hourlyRateSnowRemoval": "",
    "billingScheduleSnowRemoval": "Monthly",
    "notesSnowRemoval": "",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  },
  {
    "id": "-",
    "name": "-",
    "ownerID": "-",
    "clientType": "Comercial",
    "address": "517 W Central Enterance",
    "propertyManagerName": "ATK",
    "lg": true,
    "isActive": true,
    "snowRemoval": true,
    "lawnCare": false,
    "scheduleLawnCare": "",
    "priceLawnCareVisit": "",
    "email": "",
    "phone": "",
    "notesLawnCare": "",
    "salt": "Yes/Maybe",
    "triggerSnowRemoval": "1 inch",
    "billingStructureSnowRemoval": "Hourly",
    "snowRemovalZeroToFive": "",
    "snowRemovalFiveToTen": "",
    "snowRemovalTenToFifthteen": "",
    "snowRemovalFifthteenToTwenty": "",
    "hourlyRateSnowRemoval": "$50/hour",
    "billingScheduleSnowRemoval": "Monthly",
    "notesSnowRemoval": "",
    "billHistory": [],
    "messages": [],
    "avaliableActions": []
  }
]

"""
let jsonData = LocationMasterListJSON.data(using: .utf8)!
let LocationMasterList = try! JSONDecoder().decode([LocationOld].self, from: jsonData)
func convertLocation(location: LocationOld)-> Location{
    return Location(
        name: location.name,
        ownerID: location.ownerID,
        clientType: location.clientType,
        address: location.address,
        propertyManagerName: location.propertyManagerName,
        lg: location.lg,
        isActive: location.isActive,
        snowRemoval: location.snowRemoval,
        lawnCare: location.lawnCare,
        scheduleLawnCare: location.scheduleLawnCare,
        priceLawnCareVisit: location.priceLawnCareVisit,
        email: location.email,
        phone: location.phone,
        notesLawnCare: location.notesLawnCare,
        salt: location.email,
        triggerSnowRemoval: location.triggerSnowRemoval,
        billingStructureSnowRemoval: location.billingStructureSnowRemoval,
        snowRemovalZeroToFive: location.snowRemovalZeroToFive,
        snowRemovalFiveToTen: location.snowRemovalFifthteenToTwenty,
        snowRemovalTenToFifthteen: location.snowRemovalTenToFifthteen,
        snowRemovalFifthteenToTwenty: location.snowRemovalFifthteenToTwenty,
        hourlyRateSnowRemoval: location.hourlyRateSnowRemoval,
        billingScheduleSnowRemoval: location.billingScheduleSnowRemoval,
        notesSnowRemoval: location.notesSnowRemoval,
        latitude: "-",
        longitude: "-",
        latitudeAcuracy: "-",
        longitudeAcuracy: "-",
        billHistory: [],
        messages: [],
        avaliableActions: [])
}
let LocationMasterListNew = LocationMasterList.map{convertLocation(location: $0)}



struct LocationNew: Identifiable, Codable, Equatable{
    var id: String
    var name: String
    var ownerID: String
    var clientType: String
    var address: String
    var propertyManagerName: String
    var lg: Bool
    var isActive: Bool
    var snowRemoval: Bool
    var lawnCare: Bool
    var scheduleLawnCare: String
    var priceLawnCareVisit: String
    var email: String
    var phone: String
    var notesLawnCare: String
    var salt: String
    var triggerSnowRemoval: String
    var billingStructureSnowRemoval: String
    var snowRemovalZeroToFive: String
    var snowRemovalFiveToTen: String
    var snowRemovalTenToFifthteen: String
    var snowRemovalFifthteenToTwenty: String
    var hourlyRateSnowRemoval: String
    var billingScheduleSnowRemoval: String
    var notesSnowRemoval: String
    var latitude: String
    var longitude: String
    var latitudeAcuracy: String
    var longitudeAcuracy: String
    var billHistory: [Bill]
    var messages: [Message]
    var avaliableActions: [Action]
    
    func hash(into hasher: inout Hasher) {
        hasher.combine(id)
    }
    
    static func ==(lhs: LocationNew, rhs: LocationNew) -> Bool {
        return lhs.name == rhs.name && lhs.id == rhs.id
    }
}


