# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'


target 'YardRemote' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YardRemote

pod 'Firebase/Core'
pod 'Firebase/Analytics'
pod 'Firebase/AppDistribution'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Functions'
pod 'Firebase/Storage'
pod 'Firebase/Crashlytics'
pod 'Firebase/DynamicLinks'
pod 'Firebase/Performance'
pod 'Firebase/Database'
pod 'Firebase/RemoteConfig'
pod 'FirebaseFirestoreSwift'

  target 'YardRemoteTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YardRemoteUITests' do
    # Pods for testing
  end

end
