# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'YardRemote Manager' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YardRemote Manager
pod 'Firebase/Firestore'
pod 'Firebase/Auth'
pod 'FirebaseFirestoreSwift'
pod 'Firebase/Storage'
pod 'Firebase/Crashlytics'
pod 'FirebaseUI'



  target 'YardRemote ManagerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YardRemote ManagerUITests' do
    # Pods for testing
  end

end

